spring:
  flyway:
    baseline-on-migrate: false
    enabled: true
    locations: classpath:db/migration
  session:
    jdbc:
      initialize-schema: never
      table-name: SPRING_SESSION
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    # https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646%23issuecomment-369388646
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/library
    username: test_user
    password: pass
    driverClassName: org.postgresql.Driver